// import runTest from './template';
// import runTest from './sprite image';
// import runTest from './move sprite';
// import runTest from './sprite alpha';
// import runTest from './container test 1';
// import runTest from './default origin test 1';
// import runTest from './bounds test 1';
// import runTest from './bounds test 2';
// import runTest from './overlap test 1';
// import runTest from './keys test 1';
// import runTest from './keys test 2';
// import runTest from './vec2 callback 1';
// import runTest from './layer test 1';
// import runTest from './renderlayer test 1';
// import runTest from './spritebatch test 1';
// import runTest from './spritebatch test 2';
// import runTest from './spritebatch test 3';
// import runTest from './spritebatch test 4';
// import runTest from './camera test 1';
// import runTest from './camera test 2';
// import runTest from './post render';
// import runTest from './multiple sprite images';
// import runTest from './over 16 textures';
// import runTest from './effect layer 1';
// import runTest from './tween 1';
// import runTest from './tween 2';
// import runTest from './render layer 1';
// import runTest from './effect layer new shader';

import runTest from './sprite image';

// import runTest from './webgl batch test';
// import runTest from './display list debug 1';
// import runTest from './cube';
// import runTest from './sphere';
// import runTest from './cube batch';
// import runTest from './phong';
// import runTest from './textured cube';
// import runTest from './new camera';
// import runTest from './cube world';
// import runTest from './cube transform';
// import runTest from './load model';
// import runTest from './geometry test';
// import runTest from './orbit camera';
// import runTest from './primitives';
// import runTest from './primitives2';
// import runTest from './materials';
// import runTest from './json model';

// import runTest from './obj model';

runTest();
