export const CONFIG_DEFAULTS = {
    BACKGROUND_COLOR: 'BackgroundColor',
    BATCH_SIZE: 'BatchSize',
    DEFAULT_ORIGIN: 'DefaultOrigin',
    MAX_TEXTURES: 'MaxTextures',
    PARENT: 'Parent',
    SIZE: 'Size',
    SCENES: 'Scenes',
    RENDERER: 'Renderer',
    AUTO: 'Auto',
    WEBGL: 'WebGL',
    CANVAS: 'Canvas',
    WEBGL_CONTEXT: 'WebGLContext',
    CANVAS_CONTEXT: 'CanvasContext',
    BANNER: 'Banner',
};
